version: '2'
services:
    adap_event-app:
        image: adap_event
        external_links:
            - adap_event-postgresql:postgresql
            - adap_event-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/adap_event
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    adap_event-postgresql:
        extends:
            file: postgresql.yml
            service: adap_event-postgresql
    adap_event-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: adap_event-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
