version: '2'
services:
    adap_event-postgresql:
        container_name: adap_event-postgresql
        image: postgres:9.5.3
        # volumes:
        #     - ~/volumes/jhipster/adap_event/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=adap_event
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
